version: "3"

services:
  book-app:
    container_name: book-app
    build:
      context: ./book-app
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - "./book-app:/projects"
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        ng serve --host 0.0.0.0
    tty: true
