version: "3"

services:
  angular:
    container_name: book-app
    build:
      context: ./book-app
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - "./book-app:/projects"
    tty: true
